### ISSUE TITLE
Use a map projection

### ISSUE THREAD

**Issue by zross** [mcSamuelDataSci/learnCBD#6]
The maps you're using from tigris are unprojected. It is good practice and better for any geoprocessing to use a map projection. A common one in CA is Teale Albers (though there might be a new one. I did this [here](https://github.com/mcSamuelDataSci/learnCBD/blob/55f7768ad84b9a91c6d648cd7c26702972939cc1/processing_scripts/processing.R#L34).

**Comment by mcSamuelDataSci** [comment]
Great, thanks. I will make sure to use a consistent projection. With my previous use of "readShapePoly" below I HAD to specify a projection, and used the one shown below**. Not sure why I used this one, but will check with our CDPH GIS folks to see if there is a standard.  I guess since some of the more recent work I was doing did not require a projection, I was in inadvertently accepting some default projection that must have been used?  

Your protection, "teale <- "+proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +ellps=GRS80 +datum=NAD83 +units=m +no_defs" " looks sort of complicated, but must be important  for certain reasons?

**
myProj        <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"  
shape_CO   <- readShapePoly(paste0(myPlace,"/NewShape/CO_shp"),proj4string=CRS(myProj))

**Comment by zross** [comment]
Your projection is not a projection actually. It's an unprojected coordinate system (WGS84) which essentially means a globe not a flat map. You should be using a "flat" map -- a projected coordinate system so that shapes, sizes and distances are more accurately computed. The one I chose is one that CA uses (used) -- but you should check to see what they use. 

It looks complicated because it has more information on how the globe is flattened, any projected coordinate system will have that level of detail, but you just copy paste -- see [here](http://spatialreference.org/ref/sr-org/california-teale-albers-nad83-projection/proj4/).

**Comment by mcSamuelDataSci** [comment]
Our GIS coordinator replied "for web page display, the web map should be Web Mercator WGS 84 projection" but did not give any more detail. I will look into this some, and will use a consistent true projection throughout the project. Do you have a recommended projection for the great state of California that uses WGS 84 and has the appropriate detail to flatten?

**Comment by zross** [comment]
You've got a different situation than what your GIS coordinator expects. Can you ask them what projection they use for static maps and for geoprocessing that will give what we want.

For "slippy maps" like a Google map their answer is exactly correct. But you have two situations:

1. Union calculations and other geoprocessing
2. Display of just one state with no tiles beneath (right?, no background map?)

For item 1 you definitely want a projected map. For item 2 if you don't have a background map then showing a projected map is better because shape/size etc are correct. See how the unprojected version looks stretched below with a wide top. Projected is a more accurate geographic representation. 

All that said, you can use unprojected if you prefer. 

Unprojected (WGS84)
![image](https://user-images.githubusercontent.com/1395177/42335170-79f04cbe-804d-11e8-8896-c1ff0aaabf2a.png)

Projected (in this case similar to Teale)

![image](https://user-images.githubusercontent.com/1395177/42335220-a34f99ac-804d-11e8-949e-e78be50d1ba0.png)

**Comment by mcSamuelDataSci** [comment]
We definitely don't want to use unprojected, and want all maps on the site to look as consistent as possible. In the demo app I sent you I was aware that the interactive map and the static maps had different projections (or lack thereof) and now have the insight to fix that, I think.  

Regarding using a "reasonable projection" (which I would like to learn more about at some point, but can not prioritize right now), I poked around the site to which you linked, looking for WGS 84 for California, and a found a number.  I grabbed this one, http://spatialreference.org/ref/sr-org/7100/proj4/, but it is clearly "rotated" counterclockwise a bit from what we want, and from the "good" proejction in your lower map above.  I will just use teale for now, or whatever the projection is in your lower map above?

Regarding the issues of cut-points and geographic aggregation, I can add them as new issues, but I think they are described in pretty good detail in the app, below the point that you have had a chance to review.  Might we be able to set up a webex next week to go over this some, or would you prefer we proceed otherwise?

**Comment by zross** [comment]
Best to keep GitHub issues as single threaded so questions about meetings and cut points etc should be in other issues or in e-mail.

**Comment by mcSamuelDataSci** [comment]
Thanks, makes sense! 

What projection did you use in the second map above?

**Comment by zross** [comment]
Teale, the link is in the first comment.

**Comment by mcSamuelDataSci** [comment]
Thanks.  You noted "similar to Teale" so I thought maybe it was based on some projected WGS84.
