### ISSUE TITLE
GitHub login in error

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/learnCBD#8]
How/where to added login and password info so I don't have to enter it each time I push something from R (and get a "fatal error" message, that does not appear to be all that fatal..)

**Comment by zross** [comment]
This one is tough for me to help with given I can't test. Chris, from my office, is the most knowledgeable and if what I suggest doesn't work we might need to enlist him to screen share with you. But try this:

Install credential manager:  https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/download/v1.16.2/GCMW-1.16.2.exe
My guess is that you'll still have to enter the password one time then no more. 

There is a discussion of this issue here: https://stackoverflow.com/questions/5343068/is-there-a-way-to-skip-password-typing-when-using-https-on-github

**Comment by mcSamuelDataSci** [comment]
This worked perfectly.  I just installed it, and it did not "ask" for any credentials whatsoever.  And, when next using Git, i was able to commit and push, and it did not "ask" for credentials then.  Thanks!
